{"version":1,"ops":[{"type":6,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1553708472,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDIwMTk2MjA4MQ=="},"target":"56eb61c99e4e3e94a0ae2d5942035ac8185f8cb8cd79fd3d45c2b5230a5cba91","message":"After specifying an Autotype sequence for a particular entry (`{PASSWORD}`), keepmenu just crashed. I wasn't able to relaunch it either by calling `keepmenu` in the terminal. I was only able to use keepmenu again after logging out and logging back in. This happens every time I try to change the autotype sequence for an entry. This is very similar to issue #23. \n\nSystem: Arch Linux (Linux LTS: 4.19.31-1)\nWindow Manager: i3-gaps\nConfig:\n\n```\n[dmenu]\ndmenu_command = rofi -config ~/main/configs/rofi -dmenu -normal-window \nl = 12\n\n[database]\npw_cache_period_min = 5\ngui_editor = vscodium --extensions-dir ~/main/configs/vscode/extensions -w\ntype_library = xdotool\nautotype_default = {USERNAME}{TAB}{PASSWORD}{ENTER}\ndatabase_1 = ~/main/configs/passwords.kdbx\n```","files":null},{"type":6,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1553723618,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDIwMjA3NTYzMw=="},"target":"56eb61c99e4e3e94a0ae2d5942035ac8185f8cb8cd79fd3d45c2b5230a5cba91","message":"After specifying an Autotype sequence for a particular entry (`{PASSWORD}`), keepmenu just crashed. I wasn't able to relaunch it either by calling `keepmenu` in the terminal. I was only able to use keepmenu again after logging out and logging back in. **(EDIT: I have to reboot my computer entirely, actually)** This happens every time I try to change the autotype sequence for an entry. This is very similar to issue #23. \n\nSystem: Arch Linux (Linux LTS: 4.19.31-1)\nWindow Manager: i3-gaps\nConfig:\n\n```\n[dmenu]\ndmenu_command = rofi -config ~/main/configs/rofi -dmenu -normal-window \nl = 12\n\n[database]\npw_cache_period_min = 5\ngui_editor = vscodium --extensions-dir ~/main/configs/vscode/extensions -w\ntype_library = xdotool\nautotype_default = {USERNAME}{TAB}{PASSWORD}{ENTER}\ndatabase_1 = ~/main/configs/passwords.kdbx\n```","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1553712761,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ3NzMwMTMwNw==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-477301307"},"message":"I think I'll add some logging that can be activated with a command line switch. You can start keepmenu from the command line and then when an error happens, you should be able to see the traceback.\n\nIn the meantime, you should be able to kill the crashed process with `killall keepmenu` so you don't have to relogin each time that happens!\n\nI can reproduce this here, so I'll dig into it when I can! Thanks for the report.","files":null},{"type":6,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1553712761,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDIwMTk5NjM5Mw=="},"target":"7043d362308068efa69edb95448374949172204257e693e574e4129f275f34e6","message":"I think I'll add some logging that can be activated with a command line switch. You can start keepmenu from the command line and then when an error happens, you should be able to see the traceback.\n\nIn the meantime, you should be able to kill the crashed process with `killall keepmenu` so you don't have to relogin each time that happens!\n\nI can reproduce this here, so I'll dig into it when I can! Thanks for the report.\n\nEdit:\n\n    Traceback (most recent call last):                                                                                                     \n      File \"/usr/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap                  \n        self.run()        \n      File \"/home/firecat53/docs/family/scott/src/projects/keepmenu/keepmenu\", line 1099, in run   \n        self.dmenu_run()\n      File \"/home/firecat53/docs/family/scott/src/projects/keepmenu/keepmenu\", line 1174, in dmenu_run\n        edit = edit_entry(self.kpo, entry)\n      File \"/home/firecat53/docs/family/scott/src/projects/keepmenu/keepmenu\", line 1001, in edit_entry\n        setattr(kp_entry, field, sel)\n      File \"/usr/lib/python3.7/site-packages/pykeepass/entry.py\", line 210, in autotype_sequence\n        self._element.find('AutoType/DefaultSequence').text = value\n    AttributeError: 'NoneType' object has no attribute 'text'","files":null},{"type":3,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1553723473,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ3NzM2MTI0OQ==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-477361249"},"message":"The thing is, I've already tried to kill keepmenu via `pkill keepmenu` and `killall keepmenu`. The next time I tried to launch it, it wouldn't start up. And recently I've realized that it's not merely logging in or logging out that solves the problem, but rather rebooting my machine entirely. I have no idea why that's the case, but it just is.","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1553725423,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ3NzM2ODI4MA==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-477368280"},"message":"That's very odd. How are you starting it?","files":null},{"type":6,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1553725423,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDIwMjA4NjI5MA=="},"target":"4974233c613023422165b622bc874e98284762152f2413706b9334cfcaeac7aa","message":"That's very odd. How are you starting it?\n\nEdit:\n\nAnd what's the output of `ps aux | grep keepmenu` ?","files":null},{"type":3,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1553761279,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ3NzQ5NTAyMg==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-477495022"},"message":"In my i3 config, I have bound shift+mod4+space to launch keepmenu (`bindsym $mod+shift+space exec keepmenu`). \n\nThe output of `ps aux | grep keepmenu` is \n\n```\nuser     5680  5.0  0.7 258808 47008 ?        S    04:14   0:00 python /usr/bin/keepmenu\nuser     5690  0.0  0.5 258808 31008 ?        S    04:14   0:00 python /usr/bin/keepmenu\nuser     5691  0.3  0.5 324344 33544 ?        Sl   04:14   0:00 python /usr/bin/keepmenu\nuser     5692  0.0  0.5 324344 31540 ?        Sl   04:14   0:00 python /usr/bin/keepmenu\nuser     5711  0.0  0.0   6580  2264 pts/0    S+   04:15   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn keepmenu\n\n```\n\nAfter trying to edit the autotype sequence of a particular entry, `ps aux | grep keepmenu` gets me:\n\n```\nuser     5680  0.3  0.7 258808 47008 ?        S    04:14   0:00 python /usr/bin/keepmenu\nuser     5690  0.0  0.5 258808 31008 ?        S    04:14   0:00 python /usr/bin/keepmenu\nuser     5692  0.0  0.5 389880 34604 ?        Sl   04:14   0:00 python /usr/bin/keepmenu\nuser     5881  0.0  0.0   6580  2224 pts/0    S+   04:18   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn keepmenu\n```\n\nAfter trying to run keepmenu again (in the terminal), I get this:\n\n```\nuser     5680  0.3  0.7 258808 47008 ?        S    04:14   0:00 python /usr/bin/keepmenu\nuser     5690  0.0  0.5 258808 31008 ?        S    04:14   0:00 python /usr/bin/keepmenu\nuser     5692  0.0  0.5 389880 34608 ?        Sl   04:14   0:00 python /usr/bin/keepmenu\nuser     5907  0.0  0.0   6580  2324 pts/0    S+   04:19   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn keepmenu\n```","files":null},{"type":3,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1555394922,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ4MzUyNDE1MA==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-483524150"},"message":"Hi, has there been any progress made on this issue? Thanks.","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1555413495,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ4MzYxODA3NA==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-483618074"},"message":"No, I haven't had time to sit down and work on it yet.","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1555628765,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ4NDcxODA2MQ==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-484718061"},"message":"This is actually a pykeepass issue when opening entries that have been brought forward from an older database. It doesn't automatically create the 'autotype_sequence' field when editing, which generates the error we are seeing.\n\nWorkaround: export your database as a CSV from KeepassXC. Import the CSV into a new database using KeepassXC . This fixes the problem for me.\n\nAs for having to reboot when keepmenu crashes: I have no idea. To me, this sounds like a problem with your system. Not being able to kill a process using `killall` or `kill -9` just isn't right! :)","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1566747810,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDUyNDY0MDA4NA==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-524640084"},"message":"Was this ever resolved for you?","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1578860248,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDU3MzQ1Mjc5Mg==","github-url":"https://github.com/firecat53/keepmenu/issues/31#issuecomment-573452792"},"message":"Please reopen if this is still an issue. Thanks!","files":null},{"type":4,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1578860248,"metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50Mjk0MTQ3NTM1OQ=="},"status":2}]}