{"version":1,"ops":[{"type":6,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1552260756,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDE5NDM5ODk0OA=="},"target":"c4d2c43605b46fb748f2729850739b2711cffcec3b7ef8d43181520395ee29a9","message":"Recently when I was using keepmenu, I noticed that it just refused to start. When I ran `keepmenu` directly in my terminal, it said:\n\n```Traceback (most recent call last):\n  File \"/usr/bin/keepmenu\", line 26, in \u003cmodule\u003e\n    from pykeepass import PyKeePass\n  File \"/usr/lib/python3.7/site-packages/pykeepass/__init__.py\", line 2, in \u003cmodule\u003e\n    from .pykeepass import PyKeePass\n  File \"/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py\", line 8, in \u003cmodule\u003e\n    from future.utils import python_2_unicode_compatible\nModuleNotFoundError: No module named 'future'\n```\n\nI have no idea why this happened. I can only guess that I updated my Arch system via `sudo pacman -Syu` and that might have updated PyKeepass in some way? I updated my system again via `yay -Syu` (for the AUR), but that didn't seem to update keepmenu. In any case, I found the solution already: I just need to install the `future` package via `pip3 install --user future`. However, I am concerned that I had to go out of my way to install something just so keepmenu wouldn't break. I would imagine Arch's package manager would have managed the dependencies for me.\n\nI just wanted to let you know. Perhaps this dependency issue can be worked out?","files":null},{"type":4,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1552260797,"metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50MjE5MjU4MTM1Nw=="},"status":2},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1552262229,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ3MTM2NzI1Mw==","github-url":"https://github.com/firecat53/keepmenu/issues/28#issuecomment-471367253"},"message":"Thanks. I submitted an [Arch bug report](https://bugs.archlinux.org/task/61968?project=5\u0026order=dateopened\u0026sort=desc). Just a packaging issue with python-pykeepass.","files":null},{"type":3,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1552297669,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ3MTQ3MTU2OA==","github-url":"https://github.com/firecat53/keepmenu/issues/28#issuecomment-471471568"},"message":"Thanks! I really appreciate the work you've done!","files":null}]}