{"version":1,"ops":[{"type":1,"author":{"id":"44a0b218d7393260eaabc9384444164cde6f064d"},"timestamp":1567571550,"metadata":{"github-id":"MDU6SXNzdWU0ODg5MzQ0MTk=","github-url":"https://github.com/firecat53/keepmenu/issues/42","origin":"github"},"title":"Error: 'bytes' object has no attribute 'encode'","message":"System: Arch Linux 4.19 LTS\n\nEvery time I try to open keepmenu, I get the error message stating 'bytes' object has no attribute 'encode'. This happened after I recently updated my version of keepmenu to the latest version (r97.6634843-1 from AUR). I haven't updated in quite some time. Not quite sure what is causing this issue.\n\nI have already tried uninstalling it and then reinstalling it via pip. (`pip3 install --user keepmenu`). Then I edited the config file to change the database path to my database. I had the exact same error with that config.","files":null}]}